# Generated by Django 4.2.20 on 2025-12-11 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentacaoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criacao', 'Criação'), ('alteracao_status', 'Alteração de Status'), ('alteracao_dados', 'Alteração de Dados'), ('adicao_item', 'Adição de Item'), ('remocao_item', 'Remoção de Item')], max_length=20)),
                ('status_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('status_novo', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='cadastros.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Pedido',
                'verbose_name_plural': 'Movimentações de Pedidos',
                'ordering': ['-data_movimentacao'],
            },
        ),
    ]
